### ISSUE TITLE
Lock does not work correctly in two finger drag

### ISSUE THREAD

**Issue by peastman** [ldo/infinirule_android#1]
I observed a bug in version 16254.1:
1. Enabled the lock icon.
2. Put one finger on the body and one on the slide, then drag in opposite directions.

Instead of interpreting this as a zoom (as you almost certainly intended), it interprets it as dragging the two halves relative to each other (even though it's supposed to be locked).  I'd suggest that two finger drags always be interpreted as zooming, regardless of where on the screen your fingers are.  But in any case, it should respect the lock option.

**Comment by ldo** [comment]
Good question. The “lock” option is really more like a “limited-slip diff” option currently—you can still push the two halves in opposite directions if you want. I think it makes more sense for pinch-zooming to require both fingers on the same side of the rule.

**Comment by peastman** [comment]
Let me describe what my experiences were.  I would carefully line up the slide, then zoom in to check the result... and find that in the process of zooming, the alignment had somehow gotten messed up.  So I would zoom back out, then carefully line it up again, and this time hit the lock icon to make absolutely certain it wouldn't get messed up, and zoom back in... and find it had still gotten messed up!  Of course, this didn't happen every time, since it depended on exactly where on the screen I happened to put my fingers.  It took quite a while to figure out what was going on.

When zooming, I naturally put my fingers near the center of the screen, so it would often happen that just by chance, one would be slightly above the midline and the other slightly below.  Having that totally change the behavior is very nonintuitive.  And if someone has enabled the lock option, that certainly means they don't want the slide moving relative to the body.

**Comment by ldo** [comment]
Learn to keep your fingers on the same part of the rule. Keep them always on the upper part and avoid accidental relative movements that way.

Lock mode is a convenience, nothing more.

Closing.
